repositories.mavenCentral()

dependencies {
    api project(':barebones-core')
    api project(':barebones-commons-file')
    api project(':barebones-viewer-api')
    api project(':barebones-os-api')
    api project(':barebones-translator')
    api project(':barebones-encoding')
    api project(":barebones-preferences")

    compileOnly 'com.google.code.findbugs:jsr305:1.3.9'
    implementation group: 'com.fifesoft', name: 'rsyntaxtextarea', version: '3.6.2'

    testImplementation 'org.testng:testng:7.11.0'
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
