# - Build configuration ------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# If set to true, the build will fail whenever a release artifact can't be generated because an external tool isn't
# available.
build.pedantic=false

# If set to true, the generated artifacts are not considered to be part of an official release.
# This impacts file names (barebones-commander-current.. instead of barebones-commander-..) as well as the metadata of
# some artifacts (the debian version number will use a timestamp, for example).
build.snapshot=true



# - Application configuration ------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Name of the application.
app.name=barebones-commander

# Copyright holder.
app.vendor=barebones-commander contributors

# barebones-commander version.
app.version=0.1.0-SNAPSHOT

# Fully qualified name of the class that starts barebones-commander.
app.main=dev.barebones.commander.Launcher

# Copyright line.
app.copyright=2002-2026 muCommander contributors; 2026 barebones-commander contributors



# - Source code configuration ------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Java version the source was written for.
source.version=1.5

# Encoding of the source code.
source.encoding=UTF-8



# - Application URLs ---------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# barebones-commander homepage.
url.homepage=https://github.com/e6qu/barebones-commander

# URL that barebones-commander should connect to to check for new versions.
url.version=https://github.com/e6qu/barebones-commander/version/version.xml

# URL to download the latest barebones-commander version.
url.download=https://github.com/e6qu/barebones-commander/#download

# URL of the latest barebones-commander JAR file.
url.jar=https://github.com/e6qu/barebones-commander/releases/latest/download/barebones-commander.jar

# URL of the barebones-commander JNLP.
url.jnlp=https://github.com/e6qu/barebones-commander/webstart/



# - External tools -----------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Path to the 7z executable.
# If this is not set, compression will be done using standard ZIP algorithms.
7za.executable=

# Password for the JAR keystore.
# If you're not Maxence, you needn't bother with this.
store.pass=

# Path to the NSIS installation dir.
# If not set, Windows executables won't be generated.
nsis.dir=

# Path to the NSIS executable file.
# This will more often than not be ${nsis.dir}/makensis.
# If not set, Windows executables won't be generated.
nsis.bin=

# Path to the launch4j installation dir.
# If not set, Windows executable won't be generated.
launch4j.dir=
