include 'barebones-core'
include 'barebones-core-preload'
include 'barebones-commons-file'
include 'barebones-commons-conf'
include 'barebones-commons-collections'
include 'barebones-commons-io'
include 'barebones-commons-runtime'
include 'barebones-commons-util'
include 'barebones-encoding'
include 'barebones-preferences'
include 'barebones-command'
include 'barebones-process'
include 'barebones-translator'
include 'barebones-protocol-api'
include 'barebones-viewer-api'
include 'barebones-os-api'
include 'barebones-os-macos'
//include 'barebones-os-macos-java8'
include 'barebones-os-linux'
include 'barebones-os-win'
include 'barebones-os-openvms'

include 'barebones-archiver'
include 'barebones-format-ar'
include 'barebones-format-bzip2'
include 'barebones-format-cpio'
include 'barebones-format-gzip'
include 'barebones-format-iso'
include 'barebones-format-libguestfs'
include 'barebones-format-lst'
include 'barebones-format-rar'
include 'barebones-format-sevenzip'
include 'barebones-format-tar'
include 'barebones-format-xz'
include 'barebones-format-zip'
include 'barebones-format-rpm'
include 'barebones-protocol-adb'
include 'barebones-protocol-ftp'
include 'barebones-protocol-dropbox'
include 'barebones-protocol-gcs'
include 'barebones-protocol-gdrive'
include 'barebones-protocol-onedrive'
include 'barebones-protocol-hadoop'
include 'barebones-protocol-nfs'
include 'barebones-protocol-http'
include 'barebones-protocol-ovirt'
include 'barebones-protocol-registry'
include 'barebones-protocol-s3'
include 'barebones-protocol-sftp'
include 'barebones-protocol-smb'
include 'barebones-protocol-vsphere'
include 'barebones-viewer-text'
include 'barebones-viewer-image'
include 'barebones-viewer-pdf'
include 'barebones-viewer-binary'
include 'barebones-bonjour'

include 'apache-bzip2'
include 'jetbrains-jediterm'
include 'sevenzipjbindings'
include 'sun-net-www'
include 'gson'
include 'kotlin-reflect'

rootProject.name = 'barebones-commander'
