include("barebones-core")
include("barebones-core-preload")
include("barebones-commons-file")
include("barebones-commons-conf")
include("barebones-commons-collections")
include("barebones-commons-io")
include("barebones-commons-runtime")
include("barebones-commons-util")
include("barebones-encoding")
include("barebones-preferences")
include("barebones-command")
include("barebones-process")
include("barebones-translator")
include("barebones-protocol-api")
include("barebones-viewer-api")
include("barebones-os-api")
include("barebones-os-macos")
include("barebones-os-linux")

include("barebones-archiver")
include("barebones-format-bzip2")
include("barebones-format-gzip")
include("barebones-format-tar")
include("barebones-format-xz")
include("barebones-format-zip")

include("barebones-protocol-nfs")
include("barebones-protocol-sftp")

include("barebones-viewer-text")

include("apache-bzip2")
include("sun-net-www")

rootProject.name = "barebones-commander"
