apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly project(':barebones-commons-file')
    compileOnly project(':barebones-commons-conf')
    compileOnly project(':barebones-commons-collections')
    compileOnly project(':barebones-commons-io')
    compileOnly project(':barebones-archiver')
    compileOnly project(':barebones-command')
    compileOnly project(':barebones-encoding')
    compileOnly project(':barebones-preferences')
    compileOnly project(':barebones-process')
    compileOnly project(':barebones-translator')
    compileOnly project(':barebones-protocol-api')
    compileOnly project(':barebones-os-api')
    compileOnly project(':barebones-viewer-api')
    compileOnly project(':barebones-core-preload')


    compileOnly 'com.formdev:flatlaf:2.2'
    compileOnly 'org.jetbrains:annotations:26.0.2-1'

    implementation 'ch.qos.logback:logback-core:1.2.13'
    implementation 'ch.qos.logback:logback-classic:1.2.13'
    implementation 'org.apache.commons:commons-collections4:4.5.0'
    implementation 'net.minidev:json-smart:2.4.10'

    implementation 'org.unix4j:unix4j-command:0.6'

    testImplementation 'org.testng:testng:7.11.0'
    testImplementation(platform('org.junit:junit-bom:5.14.1'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
    testImplementation project(':barebones-commons-file')
    testImplementation project(':barebones-commons-conf')
    testImplementation project(':barebones-commons-collections')
    testImplementation project(':barebones-commons-io')
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useTestNG()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
