dependencies {
    api project(':barebones-core')
    api project(':barebones-viewer-api')
    api project(':barebones-translator')

    comprise 'com.github.pcorless.icepdf:icepdf-viewer:7.3.1'
    comprise 'com.twelvemonkeys.imageio:imageio-psd:3.12.0'
    comprise 'org.apache.avalon.framework:avalon-framework-api:4.3.1'
    implementation 'org.jmdns:jmdns:3.5.5'

    // Use JUnit test framework
    testImplementation(platform('org.junit:junit-bom:5.14.1'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

repositories.mavenCentral()

jar {
    from configurations.comprise.collect { it.isDirectory() ? it : zipTree(it) }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    bundle {
        bnd ('Bundle-Name': 'barebones-commander-viewer-pdf',
                'Bundle-Vendor': 'barebones-commander',
                'Bundle-Description': 'Library for viewing PDF files',
                'Bundle-DocURL': 'https://github.com/e6qu/barebones-commander',
                'Export-Package': 'dev.barebones.commander.viewer.pdf',
                'Import-Package':
                        '!com.sun.*,' +
                                '!javax.media.*,' +
                                '!com.ibm.uvm.tools,' +
                                '!magick,' +
                                '!com.inet.jortho,' +
                                '!org.apache.log.*,' +
                                '*',
                'Bundle-Activator': 'dev.barebones.commander.viewer.pdf.Activator',
                'Specification-Title': "barebones-commander",
                'Specification-Vendor': "barebones-commander contributors",
                'Specification-Version': project.version,
                'Impxlementation-Title': "barebones-commander",
                'Implementation-Vendor': "barebones-commander contributors",
                'Implementation-Version': revision,
                'Build-Date': new Date().format('yyyyMMdd'))
        bnd('-fixupmessages': '^Classes found in the wrong directory: .*')
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
