name: Bug Report
description: File a bug report for muCommander
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happend
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: When I did this all of sudden...
      value:
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Specific steps to reproduce
      placeholder: Go to... Click on...
      value:
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: It should appear this and this
      value:
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happens
      placeholder: But actually this or that appeared
      value:
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots?
      description: Add a screenshot if it helps explain the problem.
      placeholder: Oh, I will try to take some screenshots...
      value:
    validations:
      required: false
  - type: textarea
    id: version
    attributes:
      label: muCommander version
      description: What version of muCommander are you running?
      placeholder: Go to About of muCommander and copy-paste the version
      value:
    validations:
      required: true
  - type: textarea
    id: java-version
    attributes:
      label: Java version
      description: What version of Java muCommander is using?
      placeholder: Go to About of muCommander and copy-paste the Java information
      value:
    validations:
      required: true
  - type: textarea
    id: os-version
    attributes:
      label: Operating System type and version
      description: What type and version of Operating System you are running muCommander on?
      placeholder: Go to About of muCommander and copy-paste the OS information
      value:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      placeholder: Go to Help->Debug console and copy-paste the information (please remove any personal information if there is any)
      render: shell
      value:
    validations:
      required: false
