name: Feature request
description: Suggest an enhancement for muCommander
title: "[Enhancement] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: expectations
    attributes:
      label: Description
      description: A clear and concise description of the feature you would like to see
      placeholder: I wish that...
    validations:
      required: true
