repositories.mavenCentral()

dependencies {
    testImplementation 'org.testng:testng:7.11.0'
}

jar {
    bundle {
        bnd ('Bundle-Name': 'barebones-commander-commons-collection',
                'Bundle-Vendor': 'barebones-commander',
                'Bundle-Description': 'Collection related utilities',
                'Bundle-DocURL': 'https://github.com/e6qu/barebones-commander',
                'Export-Package': 'dev.barebones.commander.commons.collections',
                'Specification-Title': "barebones-commander",
                'Specification-Vendor': "barebones-commander contributors",
                'Specification-Version': project.version,
                'Implementation-Title': "barebones-commander",
                'Implementation-Vendor': "barebones-commander contributors",
                'Implementation-Version': revision,
                'Build-Date': new Date().format('yyyyMMdd'))
    }
}
