repositories.mavenCentral()

dependencies {
    api project(':barebones-commons-file')
    api project(':barebones-commons-util')
    api project(':barebones-protocol-api')
    api project(':barebones-translator')

    implementation 'org.ovirt.engine.api:sdk:4.4.5'

    testImplementation 'org.testng:testng:7.11.0'
    testImplementation files(project(':barebones-commons-file').sourceSets.test.output)
}

jar {
    bundle {
        bnd ('Bundle-Name': 'barebones-commander-oVirt',
                'Bundle-Vendor': 'barebones-commander',
                'Bundle-Description': 'Plugin for browsing/uploading/downloading virtual disks from oVirt',
                'Bundle-DocURL': 'https://github.com/e6qu/barebones-commander',
                'Export-Package': 'dev.barebones.commander.commons.protocol.ovirt',
                'Bundle-Activator': 'dev.barebones.commander.commons.file.protocol.ovirt.Activator',
                'Specification-Title': "barebones-commander",
                'Specification-Vendor': "barebones-commander contributors",
                'Specification-Version': project.version,
                'Implementation-Title': "barebones-commander",
                'Implementation-Vendor': "barebones-commander contributors",
                'Implementation-Version': revision,
                'Build-Date': new Date().format('yyyyMMdd'))
    }
}
