// In this section you declare where to find the dependencies of your project
repositories.mavenCentral()

dependencies {
    api project(':barebones-commons-file')
    api project(':apache-bzip2')

    implementation 'org.apache.commons:commons-compress:1.28.0'

    testImplementation 'org.testng:testng:7.11.0'
}

jar {
    bundle {
        bnd ('Bundle-Name': 'barebones-commander-tar',
                'Bundle-Vendor': 'barebones-commander',
                'Bundle-Description': 'Library with configuration tools',
                'Bundle-DocURL': 'https://github.com/e6qu/barebones-commander',
                'Export-Package': 'dev.barebones.commander.commons.file.archive.tar',
                'Specification-Title': "barebones-commander",
                'Specification-Vendor': "barebones-commander contributors",
                'Specification-Version': project.version,
                'Implementation-Title': "barebones-commander",
                'Implementation-Vendor': "barebones-commander contributors",
                'Implementation-Version': revision,
                'Build-Date': new Date().format('yyyyMMdd'),
                'Bundle-Activator': 'dev.barebones.commander.commons.file.archive.tar.Activator')
    }
}

