// In this section you declare where to find the dependencies of your project
repositories.mavenCentral()

dependencies {
    api project(':barebones-commons-file')
    api project(':apache-bzip2')

    implementation 'org.apache.commons:commons-compress:1.28.0'

    testImplementation 'org.testng:testng:7.11.0'
}


