repositories.mavenCentral()

dependencies {
    api project(':barebones-commons-file')
    api project(':barebones-core')
    api project(':barebones-translator')

    implementation 'org.jmdns:jmdns:3.5.5'

    testImplementation 'org.testng:testng:7.11.0'
}

jar {
    bundle {
        bnd ('Bundle-Name': 'barebones-commander-bonjour',
                'Bundle-Vendor': 'barebones-commander',
                'Bundle-Description': 'Menu of Bonjour services',
                'Bundle-DocURL': 'https://github.com/e6qu/barebones-commander',
                'Export-Package': 'dev.barebones.commander.bonjour',
                'Import-Package': '*',
                'Bundle-Activator': 'dev.barebones.commander.bonjour.Activator',
                'Specification-Title': "barebones-commander",
                'Specification-Vendor': "barebones-commander contributors",
                'Specification-Version': project.version,
                'Implementation-Title': "barebones-commander",
                'Implementation-Vendor': "barebones-commander contributors",
                'Implementation-Version': revision,
                'Build-Date': new Date().format('yyyyMMdd'))
    }
}
