dependencies {
    api project(':barebones-commons-file')
    api project(':barebones-protocol-api')
    api project(':barebones-encoding')
    api project(':barebones-translator')

    implementation 'com.dropbox.core:dropbox-core-sdk:7.0.0'
    implementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'

    testImplementation(platform('org.junit:junit-bom:5.14.1'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
    testImplementation 'org.testng:testng:7.11.0'
}

repositories.mavenCentral()

jar {
    bundle {
        bnd ('Bundle-Name': 'barebones-commander-dropbox',
                'Bundle-Vendor': 'barebones-commander',
                'Bundle-Description': 'Plugin for Dropbox',
                'Bundle-DocURL': 'https://github.com/e6qu/barebones-commander',
                'Export-Package': 'dev.barebones.commander.commons.file.protocol.dropbox',
                'Import-Package': 'com.google.api.client.auth.oauth2,*',
                'Bundle-Activator': 'dev.barebones.commander.commons.file.protocol.dropbox.Activator',
                'Specification-Title': "barebones-commander",
                'Specification-Vendor': "barebones-commander contributors",
                'Specification-Version': project.version,
                'Implementation-Title': "barebones-commander",
                'Implementation-Vendor': "barebones-commander contributors",
                'Implementation-Version': revision,
                'Build-Date': new Date().format('yyyyMMdd'))
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
