repositories.mavenCentral()

dependencies {
    api project(':barebones-commons-file')
    api project(':barebones-protocol-api')
    api project(':barebones-translator')

    testImplementation 'org.testng:testng:7.11.0'
    testImplementation project(':barebones-commons-file')
    testImplementation files(project(':barebones-commons-file').sourceSets.test.output)
}

jar {
    bundle {
        bnd ('Bundle-Name': 'barebones-commander-http',
                'Bundle-Vendor': 'barebones-commander',
                'Bundle-Description': 'Plugin for HTTP protocol',
                'Bundle-DocURL': 'https://github.com/e6qu/barebones-commander',
                'Export-Package': 'dev.barebones.commander.commons.file.protocol.http',
                'Bundle-Activator': 'dev.barebones.commander.commons.file.protocol.http.Activator',
                'Specification-Title': "barebones-commander",
                'Specification-Vendor': "barebones-commander contributors",
                'Specification-Version': project.version,
                'Implementation-Title': "barebones-commander",
                'Implementation-Vendor': "barebones-commander contributors",
                'Implementation-Version': revision,
                'Build-Date': new Date().format('yyyyMMdd'))
    }
}
