dependencies {
    api project(':barebones-commons-file')
    api project(':barebones-protocol-api')
    api project(':barebones-translator')
    api project(':sun-net-www')

    // Use JUnit test framework
    testImplementation(platform('org.junit:junit-bom:5.14.1'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
    testImplementation 'org.testng:testng:7.11.0'
    testImplementation project(':barebones-commons-file')
    testImplementation files(project(':barebones-commons-file').sourceSets.test.output)
}

repositories {
    mavenCentral()
}


test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
