name: Stable Build

on:
  workflow_dispatch:

jobs:
  create-release:

    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.mucommander_version.outputs.VERSION }}
      full_version: ${{ steps.mucommander_version.outputs.FULL_VERSION }}

    steps:
      - uses: actions/checkout@v3

      - name : Get version
        id: mucommander_version
        run: |
          echo "FULL_VERSION=$(${{github.workspace}}/gradlew -q printFullVersionName)" >> $GITHUB_OUTPUT
          echo "VERSION=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_OUTPUT

      - name: Create a new release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          name: "${{ steps.mucommander_version.outputs.VERSION }}"
          tag_name: "${{ steps.mucommander_version.outputs.FULL_VERSION }}"
          prerelease: false
          draft: true
          target_commitish: "${{ github.ref_name }}"

  upload-macos-artifacts:

    runs-on: macos-latest
    needs: create-release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout 'release'
        uses: actions/checkout@v3
        with:
          repository: mucommander/release
          path: release
          token: ${{ secrets.RELEASE_REPO_TOKEN }}

      - name: Apply 'release' patches
        run: |
          git config --global user.name gh-action
          git config --global user.email gh-action
          git am release/0001-set-credentials-to-Google-Drive.patch
          git am release/0002-set-credentials-to-Dropbox.patch

      - uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Build dmg
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dmg

      - name: Upload dmg
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: "./build/distributions/mucommander-${{ needs.create-release.outputs.full_version }}.dmg"
          asset_content_type: application/octet-stream

  upload-linux-artifacts:

    runs-on: ubuntu-latest
    needs: create-release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Checkout 'release'
        uses: actions/checkout@v3
        with:
          repository: mucommander/release
          path: release
          token: ${{ secrets.RELEASE_REPO_TOKEN }}

      - name: Apply 'release' patches
        run: |
          git config --global user.name gh-action
          git config --global user.email gh-action
          git am release/0001-set-credentials-to-Google-Drive.patch
          git am release/0002-set-credentials-to-Dropbox.patch

      - name: Build portable, tgz, deb, and rpm
        uses: gradle/gradle-build-action@v2
        with:
          arguments: tgz portable deb rpm

      - name: Upload portable
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: "./build/distributions/mucommander-${{ needs.create-release.outputs.full_version }}-portable.zip"
          asset_content_type: application/zip

      - name: Upload tgz
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: "./build/distributions/mucommander-${{ needs.create-release.outputs.full_version }}.tgz"
          asset_content_type: application/gzip

      - name: Upload deb
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: "./build/distributions/mucommander_${{ needs.create-release.outputs.full_version }}_amd64.deb"
          asset_content_type: application/octet-stream

      - name: Upload rpm
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: "./build/distributions/mucommander-${{ needs.create-release.outputs.full_version }}.x86_64.rpm"
          asset_content_type: application/octet-stream


  upload-windows-artifacts:

    runs-on: windows-latest
    needs: create-release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Checkout 'release'
        uses: actions/checkout@v3
        with:
          repository: mucommander/release
          path: release
          token: ${{ secrets.RELEASE_REPO_TOKEN }}

      - name: Apply 'release' patches
        run: |
          git config --global user.name gh-action
          git config --global user.email gh-action
          git am release/0001-set-credentials-to-Google-Drive.patch
          git am release/0002-set-credentials-to-Dropbox.patch

      - name: Build msi
        uses: gradle/gradle-build-action@v2
        with:
          arguments: msi

      - name: Upload msi
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: "./build/distributions/mucommander-${{ needs.create-release.outputs.version }}.msi"
          asset_content_type: application/octet-stream

